/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller
import taller.ManiobrasTrenes._

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())

    val objEstacion = new Estacion()

    val e1 = (List('a', 'b', 'c', 'd'), Nil, Nil)
    val e2 = objEstacion.aplicarMovimiento(e1, Uno(2))
    val e3 = objEstacion.aplicarMovimiento(e2, Dos(3))
    val e4 = objEstacion.aplicarMovimiento(e3, Dos(-1))
    val e5 = objEstacion.aplicarMovimiento(e4, Uno(-2))

    println(e1)
    println(e2)
    println(e3)
    println(e4)
    println(e5)

  }

  def greeting(): String = "Hello, world!"
}
